### ISSUE TITLE
JwtPayload optimization

### ISSUE THREAD

**Issue by kingcean** [mauget/jwt#1]
Suggest update `JwtApi/Models/JwtPayload.cs` as following to add further standardized claims supports.

```csharp
using System.Runtime.Serialization;
using Trivial.Security;

namespace JwtApi.Models
{
    /// <summary>
    /// A model of a JWT payload for a specific application-of-interest.
    /// </summary>
    [DataContract]
    public class JwtPayload : JsonWebTokenPayload
    {
        [DataMember(Name = "manager", EmitDefaultValue = false)]
        public bool IsManager { get; set; }

        [DataMember(Name = "admin", EmitDefaultValue = false)]
        public bool IsAdmin { get; set; }
    }
}
```

Example for JSON format (body of `POST /api/Jwt`).

```json
{
    "sub": "JWT Demo",
    "iss": "lem",
    "aud": ["Developer"],
    "exp": 1577203200,
    "manager": false,
    "admin": true
}
```

P.S.:
a. The type of expiration claim (`exp`) and other date type claims is Unix timestamp;
b. The audience claim (`aud`) supports case-sensitive string array of one or more audience identifiers;
c. Also contain claims JWT ID (`jti`), available start time (`nbf`), issue creation time (`iat`), etc.

**Comment by mauget** [comment]
Will fix/add/adjust

**Comment by mauget** [comment]
Thanks, **kingcean**:  I Implemented suggestions from [https://github.com/kingcean](https://github.com/kingcean). The demo 
+ accepts a more-generalized standard claim list, 
+ properly maps its optional boolean claims, 
+ and accepts a list of audience strings. 

I updated code docs as well.  This is reflected in Swagger UI.
-- Lou Mauget
